### PR TITLE
Upgrade code for latest version of the click module and sphinx software

### LINKED ISSUE #131: Click version 7.0 changes command names and breaks documentation generation
Version 7.0 of click introduced a change in the way the python module names commands defined by a python function (see [click changelog for version 7.0](https://click.palletsprojects.com/en/7.x/changelog/#version-7-0) ):

- `Subcommands that are named by the function now automatically have the underscore replaced with a dash. If you register a function named my_command it becomes my-command in the command line interface.`

MSNoise commands like `scan_archive` are therefore renamed `scan-archive`, etc.

This not only changes the way msnoise should be used, but also breaks the generation of the documentation. Below is the error message produced by the code in the current master branch:
```python
doc$ make html
sphinx-build -b html -d .build/doctrees   . .build/html
Running Sphinx v1.8.2
No db.ini file in this directory, please run 'msnoise db init' in this folder to initialize it as an MSNoise project folder.

Configuration error:
There is a programmable error in your configuration file:

Traceback (most recent call last):
  File "/home/xavier/.virtualenvs/msnoise-dev/lib/python3.5/site-packages/sphinx/config.py", line 368, in eval_config_file
    execfile_(filename, namespace)
  File "/home/xavier/.virtualenvs/msnoise-dev/lib/python3.5/site-packages/sphinx/util/pycompat.py", line 150, in execfile_
    exec_(code, _globals)
  File "/home/xavier/Documents/Infra/Msnoise/devel/msnoise.gitlab/doc/conf.py", line 125, in <module>
    c = click.Context(command=eval('M.%s'%command))
  File "<string>", line 1, in <module>
AttributeError: module 'msnoise.scripts.msnoise' has no attribute 'compute'

Makefile:45: recipe for target 'html' failed
make: *** [html] Error 2
```

This change of behaviour probably also introduces other undesired changes.

### PR DESCRIPTION
**Pull request by XavierBeguin**
Hi Thomas,

More changes \o/ Sorry, I know that makes a lot of PR in a short time (and I have more waiting in other branches), but I prefer to move forward by submitting most of my work, or I will get lost. I will take care to rebase later as the first PR get merged.

This is built on top of #124 and mostly fixes the code to take into account changes in latest version of click and sphinx, and should resolve #131 and #132.  One would need to update their virtual environment before using theses changes: changes should be compatible with older version of click, but not with older version of sphinx_bootstrap_theme and sphinx.

I tried to isolate most changes in different commits, and I think the commit logs are mostly self-explanatory, but do not hesitate to ask if something is unclear.

thanks,
Xavier.

### CODE REVIEW

**Comment by ThomasLecocq** [comment]
Hello Xavier,
thanks for this, so this PR should be merged first, right ?

**Comment by XavierBeguin** [comment]
As it also contains changes introduced by PR #124 (which was probably not a good idea on my part), this is now easier to merge #124 first, then merge this PR. In the end, the order won't make much difference anyway, I would say.
